project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "Lapix - Deep learning tutorials"
  site-url: "https://lapix-ufsc.github.io/dl-tutorials"
  description: "This repository contains demonstrations done with deep learning computer vision models."
  repo-branch: main
  repo-url: "https://github.com/lapix-ufsc/dl-tutorials/"
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  search: 
    location: navbar
    type: overlay
  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/lapix-ufsc/dl-tutorials/
  sidebar:
    style: floating

metadata-files: [sidebar.yml]
