name: Build docs
on:
  pull_request:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U --pre nbdev
          pip install -r requirements-dev.txt
        shell: bash
      - name: Install quarto (doc builder)
        run: |
          curl -LO https://www.quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i *64.deb && rm *64.deb
        shell: bash
      - run: nbdev_docs
        shell: bash