name: Build docs
on:
  pull_request:
jobs:
  doc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U nbdev==2.1.6
          pip install -r requirements-dev.txt
        shell: bash
      - name: Install quarto (doc builder)
        run: |
          curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.0.36/quarto-1.0.36-linux-amd64.deb # https://www.quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i *64.deb && rm *64.deb
        shell: bash
      - run: nbdev_docs
        shell: bash