name: Build docs
on:
  pull_request:
jobs:
  doc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install quarto (doc builder)
        run: |
          curl -LO https://www.quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i *64.deb && rm *64.deb
        shell: bash
      - run: quarto render tutorials/
        shell: bash